[package]
name = "yes"
version = "0.1.0"
edition = "2021"
description = "Yes."
repository = "https://github.com/mkroening/yes"
license = "MIT OR Apache-2.0"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
